[build]
# Configuration for these lints should be placed in `.clippy.toml` at the crate root.
rustflags = ["-Dwarnings"]

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-args=-z stack-size=268435456", 
  "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
]

[unstable]
build-std = ["panic_abort", "std"]
